name: reflected_mustache
version: 1.0.12

author: Mike Mitterer <office@mikemitterer.at>
description: Mustache template library
homepage: https://github.com/MikeMitterer/relected_mustache

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  analyzer: '>=0.36.0 <0.39.0'
  build: ^1.2.0
  build_resolvers: ^1.2.0
  build_config: ^0.4.0
  build_runner: ^1.7.0
  build_runner_core: ^4.1.0
  dart_style: ^1.2.3
  glob: ^1.2.0
  logging: ^0.11.0
  package_config: ^1.1.0
  package_resolver: ^1.0.0
  path: ^1.6.0
  source_span: ^1.5.0
#  reflectable: ^2.0.0
    # path: /Volumes/Daten/DevLocal/DevDart/reflectable

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
                     
